- css/app.styl
In Linux, the composer box overlaps the scroll bar a bit:
This change makes it not do that:
> minor tweak to composer css

- lib/elements/composer.js
Some improvements to autocomplete:
- convert source and candidate to lower case before checking for matches
- change to match the beginning of the string only
- if matched, replace the whole string with an appropriately cased string
> Improve autocomplete

- lib/elements/composer.js
This gives a bit nicer experience when jamming on the tab key for autocomplete while still allowing users to tab to another element when the composer is empty.
> Prevent tabbing away from composer if text is present

- css/app.styl
- lib/rich-message.js
- package.json
So `markdown-it-emoji` inserts unicode emoji which do not render on some platforms like Linux. This PR feeds the unicode into twemoji which turns it into an `<img>`.
> Use twemoji so emoji work for all

- package.json
related to atom/electron#1295
adds a super dumb module for dealing with chromium/electron-related log spew;
WARNING/ERROR are still allowed through
> squash unwanted log messages

- package.json
github-current-user@2.4.1 incorporates https://github.com/beaugunderson/github-current-user/pull/7 - this makes `friends` work out-of-the-box on my Windows 8 x64 machine
> Update dependency (Windows compat)

- app.js
The dock api is only available on osx and the dock object will be
completely missing on other systems. If it's unavailable don't bother
trying to set the badge
> don't crash when app.dock api is unavailable

- package.json
substack's excellent https://npmjs.com/mkdirp helps npm scripts work crossplatform.
This patch lets `npm start` work on my Windows 8 x64 machine.
> change mkdir -p to npm.im/mkdirp (windows compat)

- package.json
Windows cmd shell cannot set environment variables with the same syntax as bash; it requires the `set` command. However, `set` is cross platform, so lets use that.
This patch makes `npm run rebuild-leveldb` on my Windows 8 x64 machine, and still works great in bash.
> use set command to override $HOME in rebuild-leveldb script (windows compat)

- .gitignore
Apologies in advance if the omission of `debug.log` from `.gitignore` is a feature and not a bug...
> add debug.log to .gitignore

- app.js
- desktop.js
- index.html
- package.json
- web.js
This is a start on a web version. It makes `app.js` more platform agnostic and creates a `desktop.js` and `web.js` for the entry points to each version.
Although further work needs to be done to get it running on the web. I'm hitting this error:
```
Error: Cannot find module '/Users/Kyle/Documents/www/friends/node_modules/protocol-buffers/brfs' from '/Users/Kyle/Documents/www/friends'
```
and I imagine a few others are not web friendly. Still looking into solutions around those.
---
`npm run web` will start a server on `localhost:9966`.
> Start on splitting web / desktop version

- package.json
beefy looks in node_modules before checking globally. Adding watchify as a dev dependency allows for not having browserify or watchify installed globally.
> add watchify as dev dependency

- app.js
- lib/command.js
This is a simple dropin patch that moves the command switch to its own file.  We can make it more OO if we want, but for now lets just get all of this out of app.js
> Move command switch to command.js

- app.js
- lib/elements/users.js
A small change to create separate lists of "active" and "idle" users. Active users are defined as a user who sent a message in the last 60 minutes.
> Show active and idle users

- .gitignore
- package.json
- pkg.js
This updates `electron-packager` version and makes it easy to package the app for the current OS or for every OS via:
`npm run package`
`npm run package-all`
> Update package script and add package-all

- lib/elements/users.js
Hey @shama what do you think?
Totally subjective, but I like the clarity of "mute Flet" vs "mute user", especially since there is no visual cue to show which user was right-clicked.
Also adding a verb in front of the github URL clarifies what will happen if that item is selected.
Just some thoughts, I'm not a UXpert here :)
> make user menu items more explicit

- app.js
- lib/signature.js
- lib/swarm.js
This PR moves the sign and verify logic out of `swarm.js` and into `lib/signature.js`. 
There are a couple reasons for this:
1. The current sign/verify logic is dependent on the filesystem and will not work in a browser. This separation will allow for an alternative way to sign/verify messages in-browser.
2. There is a need to push `swarm.js` into its own module so its reusable by peerbot/friends-irc/other bots. Abstracting signature will help to keep this future module focused. Also bots probably don't need to sign/verify.
Please yell at me if this is outrageous. :grin:
> Separate sign and verify from swarm.js

- pkg.js
I realize now that `--prune` already handles removing devDependencies!
> Remove redundant devDep ignore step as prune does this already.

- lib/elements/input-prompt.js
We are in the process of adding back the rule `padded-blocks` into `standard`. It was temporarily disabled because of a bug in eslint which now has been fixed.
This pull request makes sure that your coding style is compliant with the new version.
Please see feross/standard#170 for more info.
> adhere to padded-blocks

- README.md
The current README has headings for `Logging In` and `Building`, and doesn't make the installation/running instructions too explicit for first-time readers (as per #147).
#146 is a good next step for simplifying this process.
> more explicit setup / installation steps

- README.md
- index.js
- package.json
- pkg.js
- version.js
Hi friends!
I encountered a show-stopping error when running `npm start` with newer node (`>= 4`). Saw this in electron JS console.
```
Uncaught Error: Module version mismatch. Expected 46, got 47.
```
Using latest electron-prebuilt and node >= 4 seemed to take care of the issue.
I bumped electron-prebuilt to latest and set engines in package.json to:
```json
"engines": {
"node": ">=4",
"npm": ">=2.8.3"
}
```
Adjusted docs to reflect the change and ran [fixpack](https://github.com/henrikjoreteg/fixpack) for good measure.
Getting things in order to take a crack at another sprint for #151.
@moose-team/owners please take a look and let me know if it's alright to forge ahead.
> use electron-prebuilt@^0.36.4, node >= 4

- lib/signature.js
broken by fba99293fd50610190df3c385a1e67ed71e0df28
should have noticed https://github.com/feross/simple-get/commit/4b61c892d4d603dfbc980329e68e0f3f940e1076
:bug: :facepunch:
> fix get.concat parameter order (changed in simple-get@2)

- app.js
- config.js
- index.js
- lib/signature.js
- package.json
- pkg.js
using `application-config-path@^0.1.0` for OS-friendly config path
note this means if you want to keep history you need to copy `friendsdb` and `public-keys` from the project directory to the application config path, which will be...
Platform | Location
--- | ---
OS X | `~/Library/Application Support/Friends/config.json`
Linux (XDG) | `$XDG_CONFIG_HOME/Friends/config.json`
Linux (Legacy) | `~/.config/Friends/config.json`
Windows (> Vista) | `%LOCALAPPDATA%/Friends/config.json`
Windows (XP, 2000) | `%USERPROFILE%/Local Settings/Application Data/Friends/config.json`
> centralize config, store db & keys in config path
